### ISSUE TITLE
After update from 0.1.4 to 0.1.5. we have issue

### ISSUE THREAD

**Issue by Ivanov-Anton** [faye/websocket-extensions-ruby#6]
![web](https://user-images.githubusercontent.com/10907664/84397989-e32a7c80-abee-11ea-9d1a-b3d21681f6f6.png)

     Failure/Error: before { visit cdrs_path }
     Net::ReadTimeout:
       Net::ReadTimeout with #<TCPSocket:(closed)>`
`

**Comment by jcoglan** [comment]
Hi @Ivanov-Anton, I would need a lot more context to be able to suggest why this might be failing, but it's quite unlikely that a network failure is related to the change in this library. Are you certain that this upgrade is the only change you made to your system to cause this error to start happening? Are you able to provide a small self-contained example that demonstrates the error happening that I could run locally?

**Comment by Ivanov-Anton** [comment]
No i can not sorry

**Comment by chamnap** [comment]
I faced a similar issue when this gem got updated to `0.1.5`. I've downgraded to `0.1.4`, and it works back locally (on `macos`), but it's still failed on `semaphoreci`, which is running on ubuntu 18.04. I'm not so sure why.

I've seen the rails controller has been finished properly and quickly, but `selenium-webdriver` got stucked. It happens when we click on an element.

<img width="1122" alt="Screen Shot 2020-06-19 at 5 03 21 PM" src="https://user-images.githubusercontent.com/407708/85121362-d6d99b80-b24e-11ea-903f-b5942845d0a7.png">

**Comment by jcoglan** [comment]
@chamnap Did you ever find out what was going on here? Were you able to upgrade to the latest version of `websocket-extensions`?

**Comment by Ivanov-Anton** [comment]
@chamnap Yes

**Comment by jcoglan** [comment]
Does that mean this issue can be closed? How did you get on @Ivanov-Anton ?

**Comment by Ivanov-Anton** [comment]
Yes you can close
